global:
  scrape_interval: 5s # Как часто собирать метрики

scrape_configs:
  - job_name: 'pr-reviewer-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080'] # 'app' — это имя сервиса в docker-compose