global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pr-reviewer-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']